BaoBoi.WebApp/Models/ErrorViewModel.cs
using System;

namespace BaoBoi.WebApp.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

BaoBoi.WebApp/Controllers/HomeController.cs
using BaoBoi.WebApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace BaoBoi.WebApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

BaoBoi.WebApp/Controllers/LixiController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BaoBoi.WebApp.Controllers
{
    public class LixiController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

BaoBoi.WebApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

BaoBoi.WebApp/Views/Lixi/Index.cshtml
@{
    ViewData["Title"] = "Lì Xì Tết";
    Layout = "/Views/Shared/_Layout.cshtml";
}
@section Styles{
    <link href="~/css/LiXiTet/Lixi.css" rel="stylesheet" />
    <link href="~/css/LiXiTet/PhaoHoa.css" rel="stylesheet" />
}
<div class="li-xi-area">
    <div class="li-xi-content">
        <div class="li-xi-title">
            @ViewBag.lixiTitle
        </div>
        <div class="li-xi-body">
            <div class="grid-lixi">
            </div>
        </div>
    </div>
</div>
<div class="phone-user unShow">
    <div class="bg-over"></div>
    <div class="phone-area">
        <div class="phone-title">
            Nhập Số Điện Thoại để Bắt Đầu!
        </div>
        <div class="phone-content">
            <input type="text" placeholder="Số Điện Thoại" class="input-phone" maxlength="14" />
        </div>
        <div class="phone-ft">
            <div class="btn-phone-xoa">Xóa</div>
            <div class="btn-phone-oke">Đồng Ý</div>
        </div>
    </div>
</div>
<div class="message unShow">
    <div class="mess-area">
        <div class="message-title"></div>
        <div class="message-content"></div>
        <div class="message-ft">
            <div class="btn-mess-ok">Đồng Ý</div>
        </div>
    </div>
</div>
<input hidden type="hidden" class="key" value="@ViewBag.Key" />
<canvas id="canvas"></canvas>

@section Scripts{
    <script src="~/js/LiXiTet/PhaoHoa.js"></script>
    <script src="~/js/LiXiTet/LiXi.js"></script>
}

BaoBoi.WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Bảo Bối Official</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/Main.css" />
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Charmonman:wght@700&display=swap" rel="stylesheet">
    <link href="~/css/Animates/Keyframes.css" rel="stylesheet" />
    @RenderSection("Styles", required: false)
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Bảo Bối Official</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Lixi" asp-action="Index">Lì Xì Tết</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="Hieu-container">
        @RenderBody()
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Bảo Bối Official - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/Main.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>